env:
  node: true
extends:
  - plugin:prettier/recommended
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 9
overrides:
  - files: [ "**/*.ts", "**/*.tsx" ]
    env:
      node: true
    extends:
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
      - plugin:prettier/recommended
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: 9
      project: ./tsconfig.json
    plugins:
      - '@typescript-eslint'
